### ISSUE TITLE
Non Ascii Issues 

### ISSUE THREAD

**Issue by leostat** [leostat/rtfm#79]
```
Traceback (most recent call last):
  File "./rtfm.py", line 755, in <module>
    run()
  File "./rtfm.py", line 132, in run
    Search(conn, sqlcmd, sqltpl, sqllst)
  File "./rtfm.py", line 154, in Search
    PrintThing(cmd)
  File "./rtfm.py", line 584, in PrintThing
    print table.table
  File "/usr/local/lib/python2.7/dist-packages/terminaltables/base_table.py", line 216, in table
    dimensions = max_dimensions(self.table_data, self.padding_left, self.padding_right)[:3]
  File "/usr/local/lib/python2.7/dist-packages/terminaltables/width_and_alignment.py", line 107, in max_dimensions
    inner_widths[i] = max(inner_widths[i], *[visible_width(l) for l in cell.splitlines()])
  File "/usr/local/lib/python2.7/dist-packages/terminaltables/width_and_alignment.py", line 28, in visible_width
    string = string.decode('u8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 94-95: unexpected end of data
```

caused by : https://github.com/aemkei/katakana.js

**Comment by g33k247** [comment]
Unable to have pretty output.
